//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DTOdbEntities : DbContext
    {
        public DTOdbEntities()
            : base("name=DTOdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourseDB> CourseDBs { get; set; }
        public virtual DbSet<DepartmentDB> DepartmentDBs { get; set; }
        public virtual DbSet<StudentDB> StudentDBs { get; set; }
    }
}
